/* Cambiá whatsapp: código de país + número, sin + ni espacios. Ej: 54911... */
window.FF = {
  CONFIG: {
    whatsapp: "5491123456789",
    shopName: "Fabian Fassi",
  },
  products: [
  {
    id: "caldera-308",
    name: "Caldera .308",
    category: "armas",
    kind: "Rifle de cerrojo",
    tag: "Caza mayor",
    image: "assets/product-rifle.jpg",
    blurb: "Cerrojo de monte. Culata de nogal, cañón mate, listo para óptica.",
    story:
      "Un rifle para jornadas largas: balance serio, gatillo limpio y una culata que no pelea con el hombro. Pensado para ciervo, jabalí y rececho. La venta se concreta con documentación vigente.",
    specs: [
      ["Calibre", ".308 Win"],
      ["Acción", "Cerrojo"],
      ["Culata", "Nogal satinado"],
      ["Cañón", "Acero mate, coronado"],
      ["Uso", "Caza mayor / rececho"],
    ],
  },
  {
    id: "apex-640",
    name: "Apex 640",
    category: "termicos",
    kind: "Visor térmico",
    tag: "Destacado",
    image: "assets/product-scope.jpg",
    blurb: "Sensor 640, imagen nítida y cuerpo para el rifle, no para la vidriera.",
    story:
      "El visor que pedís cuando el animal está lejos y la luz ya no alcanza. Paletas de caza, menú corto y un recubrimiento que aguanta humedad y roce. Ideal si ya tenés plataforma y querés dar el salto térmico.",
    specs: [
      ["Sensor", "640 × 512 · 12 μm"],
      ["Pantalla", "AMOLED FHD"],
      ["Detección", "Hasta 2.400 m"],
      ["Protección", "IP67"],
      ["Montaje", "Riel compatible"],
    ],
  },
  {
    id: "trace-35",
    name: "Trace 35",
    category: "termicos",
    kind: "Monocular térmico",
    tag: "Lo más pedido",
    image: "assets/product-thermal.jpg",
    blurb: "Cabe en el pecho. Localizás, señalás y recién ahí armás.",
    story:
      "Monocular de mano para el que camina. Encendido rápido, silueta clara y peso que no molesta en el arnés. Es el primer térmico que recomiendo si todavía no querés comprometer el visor diurno.",
    specs: [
      ["Lente", "35 mm"],
      ["Sensor", "384 / 640 según versión"],
      ["Peso", "Compacto de mano"],
      ["Batería", "Jornada completa"],
      ["Salida", "Grabación y Wi-Fi"],
    ],
  },
  {
    id: "orion-clip",
    name: "Orión Clip",
    category: "termicos",
    kind: "Clip-on térmico",
    tag: "Sin cambiar el visor",
    image: "assets/product-clipon.jpg",
    blurb: "Pasás de día a térmico sin desarmar el arma.",
    story:
      "Se adelanta al visor que ya tenés puesto. Conservás la retícula, el zero y la costumbre del ojo. Para quien no quiere dos rifles ni perder la óptica diurna en la misma salida.",
    specs: [
      ["Tipo", "Clip-on 640"],
      ["Acople", "Delante del visor"],
      ["Cero", "Se mantiene el diurno"],
      ["Cuerpo", "Compacto y liviano"],
      ["Uso", "Rececho y espera"],
    ],
  },
  {
    id: "bruma-10x42",
    name: "Bruma 10×42",
    category: "optica",
    kind: "Prismáticos",
    tag: "Óptica de campo",
    image: "assets/product-binoculars.jpg",
    blurb: "10 aumentos, cuerpo sellado, correa que no se clava.",
    story:
      "Los binoculares que se quedan en el pecho todo el día. Contraste de monte, enfoque rápido y un grip que no resbala con rocío. Si cazás rececho, esto entra antes que cualquier visor.",
    specs: [
      ["Aumentos", "10×42"],
      ["Prismas", "Techo, fase corregida"],
      ["Sellado", "Nitrogenado"],
      ["Foco", "Rueda central"],
      ["Correa", "Cuero / textil"],
    ],
  },
  {
    id: "pulse-1500",
    name: "Pulse 1500",
    category: "optica",
    kind: "Telémetro láser",
    tag: "Distancia real",
    image: "assets/product-rangefinder.jpg",
    blurb: "Medís, compensás y no adivinás el vuelo.",
    story:
      "Telémetro chico, lectura clara y alcance de verdad en campo abierto. Para quien ya tiene tabla de caída y no quiere errar por vanidad. Cabe en el bolsillo del chaleco.",
    specs: [
      ["Alcance", "Hasta 1.500 m"],
      ["Modos", "Caza / lluvia / ángulo"],
      ["Pantalla", "OLED de alto contraste"],
      ["Cuerpo", "Compacto sellado"],
      ["Alim.", "Pila estándar"],
    ],
  },
  {
    id: "nv-duo",
    name: "NV Duo 4K",
    category: "vision",
    kind: "Visión nocturna",
    tag: "Digital 4K",
    image: "assets/product-nv.jpg",
    blurb: "Cuando el térmico sobra y la luna no alcanza.",
    story:
      "Binocular digital para identificación a corta y media distancia. Sirve en puesto, control de predadores y esas noches en las que el calor no cuenta toda la historia. Grabación incluida.",
    specs: [
      ["Sensor", "Digital 4K"],
      ["Formato", "Binocular de mano"],
      ["IR", "Iluminador integrado"],
      ["Grabación", "Foto y video"],
      ["Uso", "Puesto y control"],
    ],
  },
  {
    id: "monte-blade",
    name: "Monte",
    category: "accesorios",
    kind: "Cuchillo de caza",
    tag: "Campo",
    image: "assets/product-knife.jpg",
    blurb: "Hoja fija, mango que no gira, funda que se queda en el cinturón.",
    story:
      "Cuchillo de trabajo, no de vitrina. Hoja para faena y monte, micarta que aguanta sangre y humedad, funda seria. El accesorio que más se pide junto con el primer rifle.",
    specs: [
      ["Hoja", "Fija, satín"],
      ["Mango", "Micarta"],
      ["Funda", "Cuero / kydex"],
      ["Uso", "Faena y campamento"],
      ["Largo", "Campo, no táctico"],
    ],
  },
  {
    id: "ombu-jacket",
    name: "Ombú",
    category: "campo",
    kind: "Chaquetón de caza",
    tag: "Silencioso",
    image: "assets/product-jacket.jpg",
    blurb: "Corte de rececho, tela muda, bolsillos que cierran de verdad.",
    story:
      "Prenda para salir antes del sol. No cruje, no brilla y tiene dónde poner telémetro, munición y las manos. Talles reales de campo, no de maniquí.",
    specs: [
      ["Tela", "Muda, resistente"],
      ["Corte", "Rececho"],
      ["Bolsillos", "Cierre y pecho"],
      ["Color", "Oliva / monte"],
      ["Talles", "Consultar"],
    ],
  },
  {
    id: "sendero-45",
    name: "Sendero 45",
    category: "campo",
    kind: "Mochila de caza",
    tag: "Carga",
    image: "assets/product-pack.jpg",
    blurb: "45 litros para jornada o pernocte corto. Portarma y silenciadores de roce.",
    story:
      "Mochila que aguanta rama, barro y el peso de un animal despostado. Acceso rápido al agua, correas que no cantan y un diseño que no parece de trekking urbano.",
    specs: [
      ["Volumen", "45 L"],
      ["Material", "Lona reforzada"],
      ["Porta", "Rifle / trípode"],
      ["Espalda", "Ventilada"],
      ["Uso", "Jornada y rececho"],
    ],
  },
  ],
};
